In [2]:
!pip install langchain langchain-community langchain-openai chromadb sentence-transformers tiktoken

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.12)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-openai
  Downloading langchain_openai-1.1.12-py3-none-any.whl.metadata (3.1 kB)
Collecting chromadb
  Downloading chromadb-1.5.5-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (0.12.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.19)
Requirement already satisfied: langgraph<1.2.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.3-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.48)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.18)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain)
  Downloading langchain_core-1.2.21-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.28.0)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.4.0-py3-none-any.whl.metadata (5.8 kB)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.42.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.24.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.40.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.38.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-35.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.7)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken) (2025.11.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.23.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.0)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting langchain-text-splitters<2.0.0,>=1.1.1 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (4.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (0.3.11)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.1->langchain) (3.6.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.14.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (1.3.1)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.73.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.40.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.40.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)

In [3]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter, CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
base_path = "/content/drive/MyDrive/book_recommendation/book_recommendation"

txt_path = base_path + "/tagged_description.txt"
csv_path = base_path + "/books_cleaned.csv"

In [6]:
from dotenv import load_dotenv
load_dotenv()

False

First, let's verify if a `.env` file exists in your `base_path`.

In [7]:
import os

dotenv_path = os.path.join(base_path, '.env')

if not os.path.exists(dotenv_path):
    print(f"No .env file found at: {dotenv_path}. Creating a dummy .env file.")
    # Example: Create a dummy .env file with an empty API key
    with open(dotenv_path, 'w') as f:
        f.write('OPENAI_API_KEY=your_api_key_here')
else:
    print(f"Found .env file at: {dotenv_path}")

# Now, explicitly load the .env file from the specified path
from dotenv import load_dotenv
load_dotenv(dotenv_path=dotenv_path)

# Verify if the variables are loaded (e.g., for OPENAI_API_KEY)
print(f"OPENAI_API_KEY loaded: {os.getenv('OPENAI_API_KEY') is not None}")

Found .env file at: /content/drive/MyDrive/book_recommendation/book_recommendation/.env
OPENAI_API_KEY loaded: True

In [8]:
import pandas as pd
books = pd.read_csv(csv_path)

In [9]:
books["tagged_description"].to_csv("txt_path",
index=False,
header=False)

In [10]:
raw_documents = TextLoader("txt_path",
                           encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=250, chunk_overlap=50 , separator="\n" )
documents = text_splitter.split_documents(raw_documents)

WARNING:langchain_text_splitters.base:Created a chunk of size 1170, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1216, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 375, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 311, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 483, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 484, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 962, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 845, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 296, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 881, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1090, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1191, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 306, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 270, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 515, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 754, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 390, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 265, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 253, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 308, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 730, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 723, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 258, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 475, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 272, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1267, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 683, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 555, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 523, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 282, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 789, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 566, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 525, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 299, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 535, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 559, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 565, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 385, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 412, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 463, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 597, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 478, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 461, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 259, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 306, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 616, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 421, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 889, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 695, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 304, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 277, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2010, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 481, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 302, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 522, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 649, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 778, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 688, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 550, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1225, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 408, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1186, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1216, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1193, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1059, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 690, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 878, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 286, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 768, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 389, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 419, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 725, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 528, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 523, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 340, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 901, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1272, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 560, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1637, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 438, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 251, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 779, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 718, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 516, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 960, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1132, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1325, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 853, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 272, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 801, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1121, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 838, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 262, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 734, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1195, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 775, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 280, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 309, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 358, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 768, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 767, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 718, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2012, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 308, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1288, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1231, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 729, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 750, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 447, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1242, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 311, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 914, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 306, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 846, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1128, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1075, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1320, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 363, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2834, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 572, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 367, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1143, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1006, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 715, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 712, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2510, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 956, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 309, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 351, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 641, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 405, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 525, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 795, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 391, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 256, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1424, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1085, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1146, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1268, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 790, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 297, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 874, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 256, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 876, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 808, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1814, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1830, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1064, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 955, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1182, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 283, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 283, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 288, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1286, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1644, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 759, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1932, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 874, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2008, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 2285, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1003, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 579, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 290, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 255, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1144, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 559, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1143, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1088, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1483, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1137, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 724, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 668, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 767, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 608, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 572, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 967, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 859, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1034, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 367, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 497, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 652, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 350, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 735, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 527, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 1017, which is longer than the specified 250
WARNING:langchain_text_splitters.base:Created a chunk of size 972, which is longer than the specified 250

In [11]:
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

/tmp/ipykernel_1847/3401734470.py:1: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [23]:
persist_directory = "/content/drive/MyDrive/book_recommendation/chroma_db"
db = Chroma.from_documents(
    documents,
    embeddings,
    persist_directory=base_path + "/chroma_db"
)
db.persist()

/tmp/ipykernel_1847/3877510792.py:7: LangChainDeprecationWarning: Since Chroma 0.4.x the manual persistence method is no longer supported as docs are automatically persisted.
  db.persist()

In [15]:
query= "A book for children about nature"
docs= db.similarity_search(query,
                                 k=10)
docs

[Document(metadata={'source': 'txt_path'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(metadata={'source': 'txt_path'}, page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."')]

In [17]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip('"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals:,9780786808069 Children will discover the excit...

In [19]:
def retrieve_semantic_recommendations(
    query: str,
   top_k: int = 10,

)-> pd.DataFrame:
  recs= db.similarity_search(query,k=50)
  books_list=[]
  for i in range (0,len(recs)):
    books_list+= [int(recs[i].page_content.strip('"').split()[0])]

  return books[books["isbn13"].isin(books_list)].head(top_k)

In [22]:
retrieve_semantic_recommendations("A book to teach children about war")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
66,9780007162994,0007162995,If I Die in a Combat Zone,Tim O'Brien,"Vietnam War, 1961-1975",http://books.google.com/books/content?id=0qUtS...,Perhaps the best book to emerge from the Vietn...,2003.0,3.95,208.0,11.0,If I Die in a Combat Zone:,9780007162994 Perhaps the best book to emerge ...
404,9780064402453,0064402452,Racso and the Rats of NIMH,Jane Leslie Conly,Juvenile Fiction,http://books.google.com/books/content?id=MgoNv...,"‘Racso, a brash and boastful little rodent, is...",1988.0,3.76,288.0,3231.0,Racso and the Rats of NIMH:,"9780064402453 ‘Racso, a brash and boastful lit..."
524,9780099483472,0099483475,All Quiet on the Western Front,Erich Maria Remarque,"World War, 1914-1918",NaN,All Quiet on the Western Front is probably the...,2005.0,3.95,216.0,1018.0,All Quiet on the Western Front:,9780099483472 All Quiet on the Western Front i...
1006,9780195168952,019516895X,Battle Cry of Freedom,James M. McPherson,History,http://books.google.com/books/content?id=09FkZ...,Filled with fresh interpretations and informat...,2005.0,4.34,867.0,22318.0,Battle Cry of Freedom:The Civil War Era,9780195168952 Filled with fresh interpretation...
1199,9780312265052,0312265050,The Naked and the Dead,Norman Mailer,Fiction,http://books.google.com/books/content?id=c66GL...,Portrays the contrasting personalities and nos...,2000.0,3.94,721.0,20541.0,The Naked and the Dead:50th Anniversary Editio...,9780312265052 Portrays the contrasting persona...
2828,9780571207992,0571207995,The Wars,Timothy Findley,Fiction,http://books.google.com/books/content?id=AqnDQ...,"Robert Ross, a sensitive nineteen-year-old Can...",2001.0,3.87,218.0,6229.0,The Wars:,"9780571207992 Robert Ross, a sensitive ninetee..."
3139,9780684813219,0684813211,Achilles in Vietnam,Jonathan Shay,Psychology,http://books.google.com/books/content?id=6EEnD...,An original and groundbreaking book that exami...,1994.0,4.24,272.0,1057.0,Achilles in Vietnam:Combat Trauma and the Undo...,9780684813219 An original and groundbreaking b...
3154,9780684844077,0684844079,Soul of the Sword,Robert L. O'Connell,Technology & Engineering,http://books.google.com/books/content?id=eoEag...,A sweeping illustrated history of war and the ...,2002.0,4.08,400.0,36.0,Soul of the Sword:An Illustrated History of We...,9780684844077 A sweeping illustrated history o...
3180,9780688085872,0688085873,A Short History of World War II,James L. Stokesbury,History,http://books.google.com/books/content?id=uDBhl...,"Despite the numerous books on World War II, un...",1980.0,3.93,416.0,454.0,A Short History of World War II:,9780688085872 Despite the numerous books on Wo...
3331,9780743253970,0743253973,A Separate Peace,John Knowles,Fiction,http://books.google.com/books/content?id=MXodm...,An American classic and great bestseller for o...,2003.0,3.57,208.0,169719.0,A Separate Peace:,9780743253970 An American classic and great be...